apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-gaming
  labels:
    app: coder-gaming
spec:
  selector:
    matchLabels:
      app: coder-gaming
  template:
    metadata:
      name: pod-1
      labels:
        app: coder-gaming
    spec:
      containers:
      - name: pod-container
        image: mauricioef/coder-gaming:1.0.0
        ports:
          - containerPort: 8080
        env:
        - name: MONGO_URL
          value: "BASE"
        - name: GOOGLE_CLIENT
          value: "CLIENT"
        - name: GOOGLE_SECRET
          value: "SECRET"