apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    app: coder-gaming
spec:
  containers:
  - name: pod-container
    image: mauricioef/coder-gaming:1.0.0
    ports:
      - containerPort: 8080
    env:
        - name: MONGO_URL
          value: "BASE"
        - name: GOOGLE_CLIENT
          value: "CLIENT"
        - name: GOOGLE_SECRET
          value: "SECRET"